version: "3.2"

services:
  majie-nginx:
    image: nginx:alpine
    network_mode: host
    container_name: majie-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  majie-frpc:
    image: alpine
    network_mode: host
    container_name: majie-frpc
    command: sh -c "/frp/frpc -c /frp/frpc.ini"
    volumes:
      - /opt/frp/frpc:/frp/frpc:ro
      - ./frpc.ini:/frp/frpc.ini:ro
